- name: play level variables 
  hosts: local
  connection: local
  vars:
    COURSE: Ansible
    DURATION: 10 HR
    TRAINER: Sivakumar
  tasks:
  - name: print couser information
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"

  tasks:
  - name: print couser information again
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"    