- name: play level variables 
  hosts: local
  connection: local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10 HR
    TRAINER: Sivakumar
  tasks:
  - name: print couser information
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Hello {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"