- name: variables from inventory
  hosts: frontend
  connection: local
  tasks:
  - name: print couse information
    ansible.builtin.debug:
      msg: "Hello Iam learning {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"